"""
E-COMMERCE ANALYTICS  |  CLAIM VERIFICATION
===========================================

Two jobs, both designed to catch the author being wrong:

  PART A - every numeric claim published in the README and the notebook is
           recomputed from data/processed/ and asserted. Narrative written before
           the numbers were in is exactly how a portfolio ends up with a
           confident sentence that the data does not support.

  PART B - every statement in every sql/*.sql file is EXECUTED against SQLite,
           and the headline aggregates are asserted equal to the pandas figures.
           This is what lets the SQL layer be described as verified rather than
           merely written: it is an independent reproduction of the Python
           results, and if the two ever disagree this script fails.

INPUT   data/processed/*.csv
        reports/insight_facts.json, segmentation_facts.json, data_quality_facts.json
        sql/*.sql
OUTPUT  console PASS/FAIL report; non-zero exit code on any failure
        reports/verification_report.md

Run: python src/verify_claims.py
"""

from __future__ import annotations

import io
import json
import sqlite3
import sys
from pathlib import Path

import numpy as np
import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parents[1]
PROCESSED = ROOT / "data" / "processed"
REPORTS = ROOT / "reports"
SQL_DIR = ROOT / "sql"

_report = io.StringIO()
_results: list[tuple[str, str, bool, str]] = []


def out(line: str = "") -> None:
    print(line)
    _report.write(line + "\n")


def check(section: str, label: str, got, want, tol: float = 0.005) -> None:
    """Assert one claim. Numeric comparisons use an absolute tolerance."""
    if isinstance(want, (int, float, np.integer, np.floating)) and not isinstance(want, bool):
        ok = abs(float(got) - float(want)) <= tol
        detail = f"got {float(got):,.4f}  want {float(want):,.4f}"
    else:
        ok = got == want
        detail = f"got {got!r}  want {want!r}"
    _results.append((section, label, ok, detail))


# ===========================================================================
# LOAD
# ===========================================================================
lines = pd.read_csv(PROCESSED / "orders_features.csv",
                    parse_dates=["order_date", "ship_date"], encoding="utf-8")
orders = pd.read_csv(PROCESSED / "orders_agg.csv",
                     parse_dates=["order_date", "ship_date"], encoding="utf-8")
customers = pd.read_csv(PROCESSED / "customer_metrics.csv",
                        parse_dates=["first_order_date", "last_order_date"], encoding="utf-8")
monthly = pd.read_csv(PROCESSED / "monthly_kpis.csv", encoding="utf-8")
rfm = pd.read_csv(PROCESSED / "rfm_segments.csv", encoding="utf-8")
retention = pd.read_csv(PROCESSED / "cohort_retention.csv", index_col=0, encoding="utf-8")
retention.columns = retention.columns.astype(int)

insight = json.loads((REPORTS / "insight_facts.json").read_text(encoding="utf-8"))
seg_facts = json.loads((REPORTS / "segmentation_facts.json").read_text(encoding="utf-8"))
dq_facts = json.loads((REPORTS / "data_quality_facts.json").read_text(encoding="utf-8"))

out("# Verification Report")
out()
out("Generated by `src/verify_claims.py`. Every row is recomputed from")
out("`data/processed/`; the SQL section is executed, not inspected.")
out()

# ===========================================================================
# PART A - published claims
# ===========================================================================
S = "A. Headline KPIs"
check(S, "total revenue = 12,642,501.91", lines["revenue"].sum(), 12_642_501.91, 0.02)
check(S, "total profit = 1,467,457.29", lines["profit"].sum(), 1_467_457.29, 0.02)
check(S, "total cost = 11,175,044.62", lines["cost"].sum(), 11_175_044.62, 0.02)
check(S, "profit margin = 11.61%",
      lines["profit"].sum() / lines["revenue"].sum() * 100, 11.6073, 0.001)
check(S, "order lines = 51,290", len(lines), 51_290)
check(S, "orders = 25,754", orders["order_key"].nunique(), 25_754)
check(S, "customers = 795", customers["customer_key"].nunique(), 795)
check(S, "products = 10,292", lines["product_id"].nunique(), 10_292)
check(S, "countries = 147", lines["country"].nunique(), 147)
check(S, "units = 178,312", lines["quantity"].sum(), 178_312)
check(S, "AOV = 490.89", orders["order_value"].mean(), 490.8947, 0.001)
check(S, "median order value = 201.30", orders["order_value"].median(), 201.2985, 0.001)
check(S, "AOV is 2.44x the median",
      orders["order_value"].mean() / orders["order_value"].median(), 2.44, 0.005)

S = "B. Growth"
yearly = lines.groupby("order_year").agg(revenue=("revenue", "sum"), profit=("profit", "sum"))
yearly["margin"] = yearly["profit"] / yearly["revenue"] * 100
check(S, "2011 revenue = 2,259,450.90", yearly.loc[2011, "revenue"], 2_259_450.90, 0.02)
check(S, "2014 revenue = 4,299,865.87", yearly.loc[2014, "revenue"], 4_299_865.87, 0.02)
check(S, "4-year growth = 90.31%",
      (yearly.loc[2014, "revenue"] / yearly.loc[2011, "revenue"] - 1) * 100, 90.3058, 0.001)
check(S, "2012 growth = 18.50%",
      (yearly.loc[2012, "revenue"] / yearly.loc[2011, "revenue"] - 1) * 100, 18.50, 0.01)
check(S, "2013 growth = 27.20%",
      (yearly.loc[2013, "revenue"] / yearly.loc[2012, "revenue"] - 1) * 100, 27.20, 0.01)
check(S, "2014 growth = 26.25%",
      (yearly.loc[2014, "revenue"] / yearly.loc[2013, "revenue"] - 1) * 100, 26.25, 0.01)
check(S, "margin stayed within 11.0-12.0% every year",
      bool((yearly["margin"] >= 11.0).all() and (yearly["margin"] <= 12.0).all()), True)
check(S, "no month had negative profit", int((monthly["profit"] < 0).sum()), 0)
check(S, "48 months, gapless", len(monthly), 48)

S = "C. Discount (the central claim)"
check(S, "discount given = 2,363,988.32", lines["discount_amount"].sum(), 2_363_988.32, 0.02)
check(S, "discount = 15.75% of list revenue",
      lines["discount_amount"].sum() / lines["list_revenue"].sum() * 100, 15.7531, 0.001)
no_disc = lines[lines["discount"] == 0]
heavy = lines[lines["discount"] > 0.5]
check(S, "margin at 0% discount = +25.32%",
      no_disc["profit"].sum() / no_disc["revenue"].sum() * 100, 25.3231, 0.001)
check(S, "margin above 50% discount = -111.02%",
      heavy["profit"].sum() / heavy["revenue"].sum() * 100, -111.0211, 0.001)
check(S, "0.0% of full-price lines lose money",
      no_disc["is_loss_making"].mean() * 100, 0.0)
check(S, "100.0% of 51%+ lines lose money",
      heavy["is_loss_making"].mean() * 100, 100.0)
check(S, "avg units 3.40 at 0% discount", no_disc["quantity"].mean(), 3.4047, 0.001)
check(S, "avg units FALL to 2.84 above 50%", heavy["quantity"].mean(), 2.8449, 0.001)
check(S, "units are lower at heavy discount, not higher",
      bool(heavy["quantity"].mean() < no_disc["quantity"].mean()), True)
above20 = lines[lines["discount"] > 0.20]
check(S, "revenue above 20% discount = 1,930,210.78", above20["revenue"].sum(), 1_930_210.78, 0.02)
check(S, "profit above 20% discount = -814,682.09", above20["profit"].sum(), -814_682.09, 0.02)
# Spearman recomputed independently of the notebook.
from scipy import stats  # noqa: E402  - imported here so the import is visibly local

rho_qty = stats.spearmanr(lines["discount"], lines["quantity"]).statistic
rho_margin = stats.spearmanr(lines["discount"], lines["profit_margin_pct"]).statistic
check(S, "rho(discount, quantity) = +0.018", rho_qty, 0.0177, 0.001)
check(S, "rho(discount, margin) = -0.669", rho_margin, -0.6691, 0.001)
check(S, "discount-quantity link is negligible (|rho| < 0.05)", bool(abs(rho_qty) < 0.05), True)

S = "D. Loss-making"
check(S, "loss-making lines = 12,544", lines["is_loss_making"].sum(), 12_544)
check(S, "loss-making share = 24.46%", lines["is_loss_making"].mean() * 100, 24.4570, 0.001)
check(S, "total loss = -920,646.16",
      lines.loc[lines["profit"] < 0, "profit"].sum(), -920_646.16, 0.02)

S = "E. Category / geography"
sub = lines.groupby("sub_category")["profit"].sum()
reg = lines.groupby("region")["profit"].sum()
mkt = lines.groupby("market")["profit"].sum()
check(S, "exactly ONE loss-making sub-category", int((sub < 0).sum()), 1)
check(S, "that sub-category is Tables", sub[sub < 0].index.tolist(), ["Tables"])
check(S, "Tables profit = -64,083.39", sub["Tables"], -64_083.39, 0.02)
check(S, "ZERO loss-making regions", int((reg < 0).sum()), 0)
check(S, "ZERO loss-making markets", int((mkt < 0).sum()), 0)
reg_margin = (lines.groupby("region").apply(
    lambda d: d["profit"].sum() / d["revenue"].sum() * 100, include_groups=False))
check(S, "thinnest region margin is Southeast Asia", reg_margin.idxmin(), "Southeast Asia")
check(S, "Southeast Asia margin = 2.02%", reg_margin.min(), 2.0185, 0.01)
check(S, "17 sub-categories", lines["sub_category"].nunique(), 17)
check(S, "13 regions", lines["region"].nunique(), 13)
check(S, "7 markets", lines["market"].nunique(), 7)

S = "F. Products"
prod = lines.groupby("product_id").agg(revenue=("revenue", "sum"), profit=("profit", "sum"),
                                       avg_discount=("discount", "mean"))
med = prod["revenue"].median()
danger = prod[(prod["revenue"] >= med) & (prod["profit"] <= 0)]
healthy = prod[(prod["revenue"] >= med) & (prod["profit"] > 0)]
check(S, "1,380 high-revenue loss-making products", len(danger), 1_380)
check(S, "their revenue = 3,037,190.88", danger["revenue"].sum(), 3_037_190.88, 0.02)
check(S, "their profit = -461,720.25", danger["profit"].sum(), -461_720.25, 0.02)
check(S, "= 24.02% of all revenue",
      danger["revenue"].sum() / prod["revenue"].sum() * 100, 24.0237, 0.001)
check(S, "their discount is 2.15x the healthy group",
      danger["avg_discount"].mean() / healthy["avg_discount"].mean(), 2.1536, 0.001)

S = "G. Customer concentration"
rev = customers["lifetime_revenue"].sort_values().to_numpy()
cum = np.concatenate([[0], np.cumsum(rev) / rev.sum()])
gini = 1 - 2 * np.trapezoid(cum, np.linspace(0, 1, len(rev) + 1))
top20 = customers["lifetime_revenue"].nlargest(int(len(customers) * .2)).sum()
check(S, "Gini = 0.180", gini, 0.1797, 0.001)
check(S, "top 20% hold 30.04% of revenue",
      top20 / customers["lifetime_revenue"].sum() * 100, 30.0365, 0.001)
check(S, "80/20 does NOT hold (top 20% well under 80%)",
      bool(top20 / customers["lifetime_revenue"].sum() < 0.5), True)
check(S, "unprofitable customers = 67", int((customers["lifetime_profit"] < 0).sum()), 67)
check(S, "min lifetime revenue = 3,892.23", customers["lifetime_revenue"].min(), 3_892.227, 0.01)
check(S, "max lifetime revenue = 40,488.07", customers["lifetime_revenue"].max(), 40_488.0708, 0.01)

S = "H. Closed-panel structure"
check(S, "ZERO one-time customers", int((customers["order_frequency"] == 1).sum()), 0)
check(S, "min orders per customer = 15", customers["order_frequency"].min(), 15)
check(S, "median orders per customer = 32", customers["order_frequency"].median(), 32.0)
check(S, "max orders per customer = 47", customers["order_frequency"].max(), 47)
check(S, "repeat purchase rate = 100%",
      (customers["order_frequency"] > 1).mean() * 100, 100.0)
check(S, "ZERO customers acquired after 2011",
      int((customers["first_order_date"].dt.year > 2011).sum()), 0)
check(S, "12 acquisition cohorts, all in 2011", customers["cohort_month"].nunique(), 12)
check(S, "exactly 1 customer dormant beyond 180 days",
      int((customers["days_since_last_purchase"] > 180).sum()), 1)
check(S, "median dormancy = 16 days", customers["days_since_last_purchase"].median(), 16.0)
check(S, "'New Customers' segment is EMPTY", int((rfm["segment"] == "New Customers").sum()), 0)
check(S, "segments partition the base", int(rfm["segment"].notna().sum()), 795)

S = "I. Retention"
avg_ret = retention.iloc[:, 1:].mean(axis=0)
periods = avg_ret.index.to_numpy(dtype=float)
valid = avg_ret.notna().to_numpy()
slope, _, _, p_val, _ = stats.linregress(periods[valid], avg_ret.to_numpy()[valid])
check(S, "retention period 0 is 100% for every cohort",
      bool((retention[0].dropna().round(0) == 100).all()), True)
check(S, "mean retention = 43.76%", avg_ret.mean(), 43.7587, 0.01)
check(S, "trend = -0.210 pp/month", slope, -0.2103, 0.001)
check(S, "trend p-value = 0.090", p_val, 0.0896, 0.001)
check(S, "no significant decay at alpha = 0.05", bool(p_val > 0.05), True)

S = "J. Returns"
measured = orders[orders["returns_measured"] == 1]
excluded = orders[orders["returns_measured"] == 0]
lines_m = lines[lines["returns_measured"] == 1]
sub_ret = lines_m.groupby("sub_category")["return_flag"].mean() * 100
check(S, "return rate (measured markets) = 5.81%", measured["return_flag"].mean() * 100, 5.8068, 0.001)
check(S, "orders excluded for no returns data = 5,037", len(excluded), 5_037)
check(S, "excluded markets are Africa, Canada, EMEA",
      sorted(excluded["market"].unique()), ["Africa", "Canada", "EMEA"])
check(S, "returned-order revenue = 818,044.14",
      measured.loc[measured["return_flag"] == 1, "order_value"].sum(), 818_044.14, 0.02)
check(S, "sub-category return spread 6.33%-9.10%", sub_ret.min(), 6.3320, 0.001)
check(S, "worst sub-category return rate = 9.10%", sub_ret.max(), 9.0956, 0.001)
check(S, "worst/best ratio = 1.44x (no hotspot)", sub_ret.max() / sub_ret.min(), 1.4364, 0.001)
check(S, "no returns hotspot (ratio < 2x)", bool(sub_ret.max() / sub_ret.min() < 2.0), True)
check(S, "measured orders = 20,717", len(measured), 20_717)
check(S, "returned orders = 1,203", int(measured["return_flag"].sum()), 1_203)
mkt_ret = measured.groupby("market")["return_flag"].mean() * 100
check(S, "market return spread 5.44%-6.11%", mkt_ret.min(), 5.4441, 0.001)
check(S, "highest market return rate = 6.11% (EU)", mkt_ret.max(), 6.1109, 0.001)
check(S, "market spread ratio = 1.12x", mkt_ret.max() / mkt_ret.min(), 1.1224, 0.001)
# The whole reason returns are coverage-filtered: quantify the understatement.
check(S, "diluted rate would be 4.67% if unmeasured counted as zero",
      orders["return_flag"].mean() * 100, 4.6711, 0.001)
check(S, "coverage filtering matters by 1.14pp",
      measured["return_flag"].mean() * 100 - orders["return_flag"].mean() * 100,
      1.1357, 0.001)

S = "K. Operations"
check(S, "ship lag min = 0", orders["ship_lag_days"].min(), 0)
check(S, "ship lag max = 7", orders["ship_lag_days"].max(), 7)
check(S, "no order shipped before it was placed",
      int((orders["ship_date"] < orders["order_date"]).sum()), 0)
check(S, "shipping cost = 1,352,815.70", lines["shipping_cost"].sum(), 1_352_815.70, 0.02)
check(S, "shipping = 10.70% of revenue",
      lines["shipping_cost"].sum() / lines["revenue"].sum() * 100, 10.7005, 0.001)
ship = lines.drop_duplicates("order_key").groupby("ship_mode")["ship_lag_days"].mean()
check(S, "Same Day is the fastest ship mode", ship.idxmin(), "Same Day")
check(S, "Standard Class is the slowest ship mode", ship.idxmax(), "Standard Class")
check(S, "ship modes are correctly ordered by speed",
      ship.sort_values().index.tolist(),
      ["Same Day", "First Class", "Second Class", "Standard Class"])

S = "L. Cleaning integrity"
check(S, "raw and clean row counts match", dq_facts["raw_orders_rows"], dq_facts["clean_rows"])
check(S, "zero duplicate rows on business fields", dq_facts["duplicate_rows_business_fields"], 0)
check(S, "zero unexplained collision groups", dq_facts["collision_groups_unexplained"], 0)
check(S, "1,590 raw ids resolved to 795 people", dq_facts["raw_customer_ids"], 1_590)
check(S, "clean customer count = 795", dq_facts["clean_customers"], 795)
check(S, "naive order key would give 25,035", dq_facts["orders_naive_key"], 25_035)
check(S, "composite order key gives 25,754", dq_facts["orders_composite_key"], 25_754)
check(S, "revenue is NET of discount (tested)", dq_facts["discount_semantics_verdict"], "net")
check(S, "NET hypothesis error is ~0", dq_facts["discount_semantics_net_median_error"], 0.0, 1e-6)
check(S, "reconciliation had 0 failures", dq_facts["reconciliation_failures"], 0)
check(S, "no impossible negative derived cost", dq_facts["derived_cost_negatives"], 0)
check(S, "3dp rounding keeps 27 discount levels", dq_facts["discount_distinct_3dp"], 27)
check(S, "2dp rounding would collapse to 23", dq_facts["discount_distinct_2dp"], 23)
check(S, "composite returns join flags 3,043 lines", dq_facts["returns_lines_composite_join"], 3_043)
check(S, "naive returns join would flag 3,050", dq_facts["returns_lines_naive_join"], 3_050)


# ===========================================================================
# PART B - execute the SQL and cross-verify against pandas
# ===========================================================================
def strip_sql_comments(sql: str) -> str:
    """Remove -- comments while respecting single-quoted string literals.

    Necessary because several comments in these files legitimately contain
    semicolons (and 00_schema.sql has a commented-out LOAD DATA statement), so a
    naive split(';') would produce fragments that are not valid SQL.
    """
    result: list[str] = []
    in_string = False
    i = 0
    while i < len(sql):
        ch = sql[i]
        if in_string:
            result.append(ch)
            if ch == "'":
                if i + 1 < len(sql) and sql[i + 1] == "'":
                    result.append(sql[i + 1])
                    i += 2
                    continue
                in_string = False
            i += 1
            continue
        if ch == "'":
            in_string = True
            result.append(ch)
            i += 1
            continue
        if ch == "-" and i + 1 < len(sql) and sql[i + 1] == "-":
            newline = sql.find("\n", i)
            if newline == -1:
                break
            i = newline
            continue
        result.append(ch)
        i += 1
    return "".join(result)


def split_statements(sql: str) -> list[str]:
    return [s.strip() for s in strip_sql_comments(sql).split(";") if s.strip()]


FACT_COLUMNS = [
    "order_line_id", "order_id", "order_key", "order_date", "ship_date", "ship_mode",
    "customer_id", "customer_key", "customer_name", "customer_segment",
    "city", "state", "country", "market", "region",
    "product_id", "product_label", "category", "sub_category", "brand",
    "quantity", "revenue", "list_revenue", "discount", "discount_amount",
    "cost", "profit", "profit_margin_pct", "shipping_cost",
    "order_priority", "return_flag", "returns_measured", "ship_lag_days",
    "is_loss_making", "discount_band", "order_year", "order_month", "order_ym",
]

out("## SQL execution")
out()

con = sqlite3.connect(":memory:")

# Build the schema from the shipped DDL, so the file itself is under test.
schema_sql = (SQL_DIR / "00_schema.sql").read_text(encoding="utf-8")
schema_statements = split_statements(schema_sql)
for stmt in schema_statements:
    con.execute(stmt)
out(f"- `00_schema.sql`: **{len(schema_statements)}** statements executed")

# Populate. Dates are written as ISO date strings so the portable
# lexicographic comparisons in customer_analysis.sql behave chronologically.
fact = lines[FACT_COLUMNS].copy()
fact["order_date"] = fact["order_date"].dt.strftime("%Y-%m-%d")
fact["ship_date"] = fact["ship_date"].dt.strftime("%Y-%m-%d")
fact.to_sql("fact_order_lines", con, if_exists="append", index=False)
loaded = con.execute("SELECT COUNT(*) FROM fact_order_lines").fetchone()[0]
check("M. SQL load", "fact_order_lines loaded 51,290 rows", loaded, 51_290)
out(f"- loaded **{loaded:,}** rows into `fact_order_lines`")
out()

executed = {}
for name in ("sales_analysis.sql", "product_analysis.sql",
             "customer_analysis.sql", "operations_analysis.sql"):
    statements = split_statements((SQL_DIR / name).read_text(encoding="utf-8"))
    rows_returned = 0
    for idx, stmt in enumerate(statements, 1):
        try:
            cur = con.execute(stmt)
            fetched = cur.fetchall()
            rows_returned += len(fetched)
            # A query that returns nothing is usually a broken predicate, not an
            # empty truth - flag it rather than let it pass silently.
            check(f"N. {name}", f"query {idx} returned rows", bool(len(fetched) > 0), True)
        except Exception as exc:  # noqa: BLE001
            check(f"N. {name}", f"query {idx} executes", False, True)
            out(f"  - **FAILED** query {idx} in `{name}`: {type(exc).__name__}: {exc}")
    executed[name] = (len(statements), rows_returned)
    out(f"- `{name}`: **{len(statements)}** queries executed, "
        f"{rows_returned:,} rows returned")

out()
out("## SQL vs pandas cross-check")
out()

S = "O. SQL agrees with pandas"


def scalar(sql: str):
    return con.execute(sql).fetchone()[0]


check(S, "SQL total revenue", scalar("SELECT SUM(revenue) FROM fact_order_lines"),
      lines["revenue"].sum(), 0.02)
check(S, "SQL total profit", scalar("SELECT SUM(profit) FROM fact_order_lines"),
      lines["profit"].sum(), 0.02)
check(S, "SQL total cost", scalar("SELECT SUM(cost) FROM fact_order_lines"),
      lines["cost"].sum(), 0.02)
check(S, "SQL order count (composite key)",
      scalar("SELECT COUNT(DISTINCT order_key) FROM fact_order_lines"),
      orders["order_key"].nunique())
check(S, "SQL customer count (resolved key)",
      scalar("SELECT COUNT(DISTINCT customer_key) FROM fact_order_lines"),
      customers["customer_key"].nunique())
check(S, "SQL reproduces the naive-order-key trap",
      scalar("SELECT COUNT(DISTINCT order_id) FROM fact_order_lines"), 25_035)
check(S, "SQL reproduces the raw-customer-id trap",
      scalar("SELECT COUNT(DISTINCT customer_id) FROM fact_order_lines"), 1_590)
check(S, "SQL loss-making line count",
      scalar("SELECT SUM(is_loss_making) FROM fact_order_lines"),
      int(lines["is_loss_making"].sum()))
check(S, "SQL discount given",
      scalar("SELECT SUM(discount_amount) FROM fact_order_lines"),
      lines["discount_amount"].sum(), 0.02)

# Category profit, row by row.
sql_cat = pd.read_sql_query(
    "SELECT category, SUM(revenue) AS revenue, SUM(profit) AS profit "
    "FROM fact_order_lines GROUP BY category ORDER BY category", con).set_index("category")
pd_cat = lines.groupby("category").agg(revenue=("revenue", "sum"), profit=("profit", "sum"))
for cat in pd_cat.index:
    check(S, f"SQL revenue matches pandas for {cat}",
          sql_cat.loc[cat, "revenue"], pd_cat.loc[cat, "revenue"], 0.02)
    check(S, f"SQL profit matches pandas for {cat}",
          sql_cat.loc[cat, "profit"], pd_cat.loc[cat, "profit"], 0.02)

# Discount band economics - the central finding, reproduced in SQL.
sql_band = pd.read_sql_query(
    "SELECT discount_band, COUNT(*) AS n, AVG(quantity) AS avg_qty, "
    "       SUM(profit) AS profit, SUM(revenue) AS revenue, "
    "       100.0 * SUM(is_loss_making) / COUNT(*) AS loss_rate "
    "FROM fact_order_lines GROUP BY discount_band", con).set_index("discount_band")
check(S, "SQL: 0.0% of full-price lines lose money",
      sql_band.loc["0% (none)", "loss_rate"], 0.0)
check(S, "SQL: 100.0% of 51%+ lines lose money",
      sql_band.loc["51%+", "loss_rate"], 100.0)
check(S, "SQL: units fall at 51%+ vs full price",
      bool(sql_band.loc["51%+", "avg_qty"] < sql_band.loc["0% (none)", "avg_qty"]), True)

# The one loss-making sub-category, found by SQL independently.
sql_loss_sub = pd.read_sql_query(
    "SELECT sub_category, SUM(profit) AS profit FROM fact_order_lines "
    "GROUP BY sub_category HAVING SUM(profit) < 0", con)
check(S, "SQL finds exactly 1 loss-making sub-category", len(sql_loss_sub), 1)
check(S, "SQL names it Tables", sql_loss_sub["sub_category"].tolist(), ["Tables"])

# Return rate, respecting coverage.
sql_ret = scalar(
    "SELECT 100.0 * SUM(returned) / COUNT(*) FROM ("
    "  SELECT order_key, MAX(return_flag) AS returned FROM fact_order_lines "
    "  WHERE returns_measured = 1 GROUP BY order_key)")
check(S, "SQL return rate matches pandas", sql_ret, measured["return_flag"].mean() * 100, 0.001)
sql_excluded = scalar(
    "SELECT COUNT(DISTINCT order_key) FROM fact_order_lines WHERE returns_measured = 0")
check(S, "SQL excluded-order count matches", sql_excluded, len(excluded))

# The coverage dimension must never claim a rate for an unmeasured market.
uncovered = pd.read_sql_query(
    "SELECT market FROM dim_returns_coverage WHERE has_returns_data = 0 ORDER BY market", con)
check(S, "coverage table flags exactly the 3 unmeasured markets",
      uncovered["market"].tolist(), ["Africa", "Canada", "EMEA"])

# RFM in SQL vs pandas. Exact equality is NOT expected - NTILE and qcut break
# ties differently - so the aggregate is asserted and the drift is reported.
sql_rfm = pd.read_sql_query("""
    WITH per_customer AS (
        SELECT customer_key, MIN(order_date) AS first_order_date,
               MAX(order_date) AS last_order_date,
               COUNT(DISTINCT order_key) AS frequency, SUM(revenue) AS monetary
        FROM fact_order_lines GROUP BY customer_key),
    scored AS (
        SELECT c.*, 6 - NTILE(5) OVER (ORDER BY c.last_order_date DESC) AS r_score,
               NTILE(5) OVER (ORDER BY c.frequency ASC) AS f_score,
               NTILE(5) OVER (ORDER BY c.monetary ASC)  AS m_score
        FROM per_customer c)
    SELECT CASE
        WHEN first_order_date >= '2014-10-02' THEN 'New Customers'
        WHEN r_score >= 4 AND (f_score + m_score) / 2.0 >= 4 THEN 'Champions'
        WHEN r_score >= 3 AND (f_score + m_score) / 2.0 >= 3 THEN 'Loyal Customers'
        WHEN r_score >= 3 THEN 'Potential Loyalists'
        WHEN r_score = 2 THEN 'At Risk'
        ELSE 'Lost Customers' END AS segment_name,
        COUNT(*) AS customers
    FROM scored GROUP BY segment_name
""", con).set_index("segment_name")["customers"]
check(S, "SQL RFM covers all 795 customers", int(sql_rfm.sum()), 795)
check(S, "SQL RFM also yields an empty New Customers segment",
      int(sql_rfm.get("New Customers", 0)), 0)
pd_counts = rfm["segment"].value_counts()
drift = {seg: int(sql_rfm.get(seg, 0)) - int(pd_counts.get(seg, 0))
         for seg in set(sql_rfm.index) | set(pd_counts.index)}
max_drift = max(abs(v) for v in drift.values())
check(S, "SQL vs pandas segment drift is small (tie-breaking only)",
      bool(max_drift <= 5), True)

con.close()


# ===========================================================================
# REPORT
# ===========================================================================
out()
out("## Results")
out()

passed = sum(1 for *_, ok, _ in ((s, l, ok, d) for s, l, ok, d in _results) if ok)
failed = len(_results) - passed

by_section: dict[str, list] = {}
for section, label, ok, detail in _results:
    by_section.setdefault(section, []).append((label, ok, detail))

for section, items in by_section.items():
    n_ok = sum(1 for _, ok, _ in items if ok)
    out(f"### {section} - {n_ok}/{len(items)} passed")
    out()
    for label, ok, detail in items:
        if ok:
            out(f"- PASS  {label}")
        else:
            out(f"- **FAIL  {label}**  ({detail})")
    out()

out(f"**TOTAL: {passed} PASS / {failed} FAIL**")
out()
if failed == 0:
    out("Every published claim is reproduced from the processed data, and the SQL layer")
    out("independently agrees with the pandas pipeline on all cross-checked aggregates.")

(REPORTS / "verification_report.md").write_text(_report.getvalue(), encoding="utf-8")

print()
print("=" * 70)
print(f"  {passed} PASS / {failed} FAIL")
print(f"  SQL executed: {sum(v[0] for v in executed.values()) + len(schema_statements)} statements")
print(f"  report: reports/verification_report.md")
print("=" * 70)

if failed:
    print("\nFAILURES:")
    for section, label, ok, detail in _results:
        if not ok:
            print(f"  [{section}] {label}\n      {detail}")
    sys.exit(1)
